export type looseFieldData = {
  display?: boolean,
  inputKey?: string,
  inputType?: string,
  inputTitle?: string,
  isRequired?: boolean,
  initialValue?: string,
  pickerData?: Array<>,
  pickerKeyDisplay?: string,
  pickerKeySave?: string,
  disabled?: boolean,
  isPickerEditable?: boolean,
  CustomElement?: any,
  params?: {},
  iconName?: string,
  needWarning?: boolean,
  shouldRenderBorder?: boolean,
  // opt out component must have CustomElement, and doesn't have any form attribute
  optOut?: boolean,
};
export type strictFieldData = {
  display: boolean,
  key: string,
  type: string,
  title: string,
  isRequired: boolean,
  initialValue: string,
  picker_data: Array<>,
  pickerKeyForDisplay: string,
  pickerKeyForSave: string,
  isDisabled: boolean,
  isPickerEditable: boolean,
  CustomElement: any,
  params: {},
  iconName: string,
  needWarning: boolean,
  shouldRenderBorder: boolean,
  optOut: boolean,
};
